#:kivy 1.9.0

<Data>:
	text: text
	img: image
	button: button

	Image:
		id: image
		source: "1.png"
		allow_stretch: True
		size: root.width,root.height
	
	Label:
		id: text
		font_size: 30
		color: 0,1,0,1
		outline_color: 1,1,1
		outline_width: 3
		halign: 'center'
		valign: 'top'
		text: ""
		size: self.texture_size
		x: (root.width - self.size[0])/2
		top: 500

	Button:
		id: button
		font_size: 20
		text_size: self.size
		text: "Take comparison picture"
		text_color: 1,1,1,1
		halign: 'center'
		valing: 'middle'
		color: 0.9,0.9,0.9,1
		size_x: 200
		size_y: 60
		size: self.size_x,self.size_y
		pos: root.width/2 - self.size_x/2, 20
		
