#:kivy 1.9.0

<Data>:
	text: text
	img: image

	Image:
		id: image
		source: "1.png"
		allow_stretch: True
		pos_center: root.center
		size: root.width,root.height
	
	AnchorLayout:
		anchor_x: 'left'
		anchor_y: 'bottom'

		Label:
			id: text
			font_size: 30
			color: 0,0,0,1
			outline_color: 1,1,1
			outline_width: 3
			size_hint: None, None
			halign: 'left'
			valign: 'bottom'
			text: ""
			size: self.texture_size
		
